[package]
name = "rticx-spsc"
version = "0.1.0"
edition = "2024"
authors = ["Zakaria Madaoui"]
description = "no_std single-producer single-consumer queue for the RTICX software tasks pass"
license = "MIT"
repository = "https://github.com/rticx-rs/rticx"
homepage = "https://github.com/rticx-rs/rticx/wiki"
keywords = ["rtic", "rticx", "spsc", "queue", "no-std"]
categories = ["no-std", "embedded", "data-structures"]
readme = "README.md"

[dependencies]
