[package]
name = "rticx-cortex-m"
version = "0.1.0"
edition = "2024"
authors = ["Zakaria Madaoui"]
description = "RTICX distribution for single-core Cortex-M targets (armv6-m and armv7-m and above)"
license = "MIT"
repository = "https://github.com/rticx-rs/rticx"
homepage = "https://github.com/rticx-rs/rticx/wiki"
keywords = ["rtic", "rticx", "cortex-m", "arm", "embedded"]
categories = ["no-std", "embedded"]
readme = "README.md"

[lib]
test = false
bench = false

[dependencies]
cortex-m = "0.7.7"
rticx-cortex-m-macro = { version = "0.1.0", path = "rticx-macro" }
rticx-sw-pass = { version = "0.1.0", path = "../../compilation-passes/rticx-sw-pass" }

[features]
default = ["swtasks"]
# Software tasks pass (enabled by default; disable to use a hardware-only distribution)
swtasks = ["rticx-cortex-m-macro/swtasks"]
# Use interrupt source-masking for locking (armv6-m: Cortex-M0/M0+/M23).
# When disabled (default), BASEPRI-based locking is used (armv7-m and above).
armv6m = ["rticx-cortex-m-macro/armv6m"]
